### PR TITLE
ui: refine Floor and Thread styles

### PR DESCRIPTION
**Pull request by BugenZhao**

### CODE REVIEW

**Comment by hebingchang** [comment]
Thanks. Would you please hide the expand button when the content is short and has already shown completely?

**Comment by skyzh** [comment]
I would suggest something like `<SplitLineText text={text} maxLoC={xxx}>`

**Comment by hebingchang** [comment]
Please run `yarn format` or `npm run format` before commit.

**Comment by skyzh** [comment]
@BugenZhao please fix conflict :)

**Pull request merged**
